In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/data_transformed.csv")

In [4]:
df.isna().sum()

event-id                        0
location-long                   0
location-lat                    0
argos:lat1                      0
argos:lat2                     85
argos:lon1                      0
argos:lon2                     85
individual-local-identifier     0
date                            0
time                            0
dtype: int64

In [5]:
df = df.dropna()

In [6]:
df.isna().sum()

event-id                       0
location-long                  0
location-lat                   0
argos:lat1                     0
argos:lat2                     0
argos:lon1                     0
argos:lon2                     0
individual-local-identifier    0
date                           0
time                           0
dtype: int64

In [7]:
import datetime as dt

In [8]:
df["year"] = df["date"].apply(lambda x: 
                                    dt.datetime.strptime(x, "%Y-%m-%d").year)


In [9]:
df["month"] = df["date"].apply(lambda x: 
                                    dt.datetime.strptime(x, "%Y-%m-%d").month)

In [10]:
df=df.drop(columns=["event-id", "date"])

In [11]:
df

location-long  location-lat  argos:lat1  argos:lat2  argos:lon1  \
0           -122.407        36.981      36.981      47.285    -122.407   
1           -122.788        37.637      37.637      39.596    -122.788   
2           -122.827        37.166      37.166      44.267    -122.827   
3           -123.466        38.184      38.184      45.262    -123.466   
4           -123.410        37.141      37.141      34.968    -123.410   
...              ...           ...         ...         ...         ...   
15540       -115.027        26.702      26.702      37.012    -115.027   
15541       -115.930        26.972      26.972      18.266    -115.930   
15542       -119.121        30.734      30.734      21.285    -119.121   
15543       -119.172        30.742      30.742      23.543    -119.172   
15544       -117.927        31.318      31.318      39.205    -117.927   

       argos:lon2 individual-local-identifier      time  year  month  
0         -69.471            1993CA-Bmu-00834  01:23:17  1993      8  
1        -132.219            1993CA-Bmu-00834  13:04:34  1993      8  
2         -86.243            1993CA-Bmu-00834  01:57:39  1993      9  
3         -88.640            1993CA-Bmu-10823  22:35:12  1993      9  
4        -133.827            1993CA-Bmu-10836  03:40:17  1993      9  
...           ...                         ...       ...   ...    ...  
15540    -165.932            2008CR-Bmu-01388  19:13:04  2008      6  
15541    -154.364            2008CR-Bmu-01388  22:27:15  2008      6  
15542     -73.036            2008CR-Bmu-01388  11:42:10  2008      6  
15543     -86.128            2008CR-Bmu-01388  11:59:00  2008      6  
15544    -157.699            2008CR-Bmu-01388  19:08:34  2008      6  

[15460 rows x 10 columns]

In [12]:
for elem in df["individual-local-identifier"].unique():
     df.loc[df["individual-local-identifier"]==elem].to_csv(f"../data/{elem}.csv")

In [13]:
df_23043 = pd.read_csv("./1999CA-Bmu-23043.csv") #individuo con la ruta más larga

In [14]:
df_23043

Unnamed: 0  location-long  location-lat  argos:lat1  argos:lat2  \
0          3173       -120.143        34.120      34.120      35.544   
1          3174       -120.145        34.147      34.147      32.243   
2          3175       -119.740        33.980      33.980      38.156   
3          3176       -119.771        34.163      34.163      28.573   
4          3177       -119.688        34.350      34.350      42.993   
..          ...            ...           ...         ...         ...   
410        3583       -122.007        21.730      21.730      22.057   
411        3584       -122.871        21.247      21.247      20.439   
412        3585       -122.755        21.083      21.083      16.252   
413        3586       -122.272        20.831      20.831      14.861   
414        3587       -122.718        19.848      19.848      23.507   

     argos:lon1  argos:lon2 individual-local-identifier      time  year  month  
0      -120.143    -127.027            1999CA-Bmu-23043  16:09:13  1999      7  
1      -120.145    -129.529            1999CA-Bmu-23043  03:27:53  1999      7  
2      -119.740    -139.994            1999CA-Bmu-23043  12:33:13  1999      7  
3      -119.771    -145.945            1999CA-Bmu-23043  23:53:08  1999      7  
4      -119.688     -76.494            1999CA-Bmu-23043  03:20:07  1999      7  
..          ...         ...                         ...       ...   ...    ...  
410    -122.007    -123.562            1999CA-Bmu-23043  16:00:28  1999     12  
411    -122.871    -119.302            1999CA-Bmu-23043  12:00:55  1999     12  
412    -122.755    -101.167            1999CA-Bmu-23043  17:16:22  1999     12  
413    -122.272    -149.760            1999CA-Bmu-23043  04:21:51  1999     12  
414    -122.718    -139.853            1999CA-Bmu-23043  16:33:51  1999     12  

[415 rows x 11 columns]

In [15]:
import tensorflow as tf
from tensorflow.data import Dataset

2021-10-16 09:56:13.640190: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-16 09:56:13.640234: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [16]:
df_23043 = df_23043.drop(columns=["Unnamed: 0", "individual-local-identifier", "time", "year", "month"])
#ballena con ruta más larga

In [17]:
df_23043

location-long  location-lat  argos:lat1  argos:lat2  argos:lon1  \
0         -120.143        34.120      34.120      35.544    -120.143   
1         -120.145        34.147      34.147      32.243    -120.145   
2         -119.740        33.980      33.980      38.156    -119.740   
3         -119.771        34.163      34.163      28.573    -119.771   
4         -119.688        34.350      34.350      42.993    -119.688   
..             ...           ...         ...         ...         ...   
410       -122.007        21.730      21.730      22.057    -122.007   
411       -122.871        21.247      21.247      20.439    -122.871   
412       -122.755        21.083      21.083      16.252    -122.755   
413       -122.272        20.831      20.831      14.861    -122.272   
414       -122.718        19.848      19.848      23.507    -122.718   

     argos:lon2  
0      -127.027  
1      -129.529  
2      -139.994  
3      -145.945  
4       -76.494  
..          ...  
410    -123.562  
411    -119.302  
412    -101.167  
413    -149.760  
414    -139.853  

[415 rows x 6 columns]

In [54]:
df_23043.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415 entries, 0 to 414
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   location-long  415 non-null    float64
 1   location-lat   415 non-null    float64
 2   argos:lat1     415 non-null    float64
 3   argos:lat2     415 non-null    float64
 4   argos:lon1     415 non-null    float64
 5   argos:lon2     415 non-null    float64
dtypes: float64(6)
memory usage: 19.6 KB


In [58]:
from tensorflow.data import Dataset

In [59]:
train_size = df_23043.shape[0] * 90//100

In [60]:
dataset= Dataset.from_tensor_slices(df_23043[:train_size])

In [61]:
dataset

<TensorSliceDataset shapes: (6,), types: tf.float64>

In [62]:
for e in dataset:
    print(e)

tf.Tensor([-120.143   34.12    34.12    35.544 -120.143 -127.027], shape=(6,), dtype=float64)
tf.Tensor([-120.145   34.147   34.147   32.243 -120.145 -129.529], shape=(6,), dtype=float64)
tf.Tensor([-119.74    33.98    33.98    38.156 -119.74  -139.994], shape=(6,), dtype=float64)
tf.Tensor([-119.771   34.163   34.163   28.573 -119.771 -145.945], shape=(6,), dtype=float64)
tf.Tensor([-119.688   34.35    34.35    42.993 -119.688  -76.494], shape=(6,), dtype=float64)
tf.Tensor([-119.641   34.06    34.06    25.755 -119.641  -78.743], shape=(6,), dtype=float64)
tf.Tensor([-120.031   34.257   34.257   31.395 -120.031 -105.779], shape=(6,), dtype=float64)
tf.Tensor([-120.053   34.32    34.32    41.271 -120.053 -153.93 ], shape=(6,), dtype=float64)
tf.Tensor([-119.815   34.124   34.124   29.721 -119.815 -140.446], shape=(6,), dtype=float64)
tf.Tensor([-119.686   34.177   34.177   41.681 -119.686  -80.803], shape=(6,), dtype=float64)
tf.Tensor([-119.755   34.097   34.097   35.982 -119.755 -128

In [114]:
n_points = 20
window_length = n_points+ 1 #20 puntos que conoce el modelo + 1 que quiero predecir 
#dataset = dataset.window(window_length, shift=1, drop_remainder=True)
dataset = tf.keras.utils.timeseries_dataset_from_array(
    df_23043, targets=None,sequence_length = window_length, sequence_stride=1, sampling_rate=1,
    batch_size=32, shuffle=False, seed=None, start_index=None, end_index=None
)

In [115]:
dataset.element_spec

TensorSpec(shape=(None, None, 6), dtype=tf.float64, name=None)

In [116]:
def mapdataset(elem):
    X,y = elem[:,:-1,:],elem[:,-1:,0:2]
    X.set_shape([None, n_points, None])
    y.set_shape([None, window_length - n_points, None])
    
    return X,y

In [117]:
new_dataset = dataset.map(mapdataset)

In [144]:
lstm_model = tf.keras.models.Sequential([
    # Shape [batch, time, features] => [batch, time, lstm_units]
    tf.keras.layers.LSTM(32, return_sequences=True),
    # Shape => [batch, time, features]
    tf.keras.layers.Dense(units=2)
])

In [148]:
MAX_EPOCHS = 20

def compile_and_fit(lstm_model, new_dataset, patience=2):
    early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss',
                                                    patience=patience,
                                                    mode='min')

    lstm_model.compile(loss=tf.losses.MeanSquaredError(),
                optimizer=tf.optimizers.Adam(),
                metrics=[tf.metrics.MeanAbsoluteError()])

    history = lstm_model.fit(new_dataset, epochs=MAX_EPOCHS,
                      #validation_data=window.val,
                      callbacks=[early_stopping])
    return history

In [149]:
history = compile_and_fit(lstm_model, new_dataset)

IPython.display.clear_output()
#val_performance['LSTM'] = lstm_model.evaluate(new_dataset.val)
performance['LSTM'] = lstm_model.evaluate(new_dataset.test, verbose=0)

Epoch 1/20
13/13 [==============================] - 1s 12ms/step - loss: 7839.0469 - mean_absolute_error: 77.1756
Epoch 2/20
13/13 [==============================] - 0s 10ms/step - loss: 7708.6064 - mean_absolute_error: 76.6547
Epoch 3/20
13/13 [==============================] - 0s 10ms/step - loss: 7546.4360 - mean_absolute_error: 75.6205
Epoch 4/20
13/13 [==============================] - 0s 9ms/step - loss: 7445.1279 - mean_absolute_error: 74.8711
Epoch 5/20
13/13 [==============================] - 0s 10ms/step - loss: 7380.0112 - mean_absolute_error: 74.3953
Epoch 6/20
13/13 [==============================] - 0s 10ms/step - loss: 7326.4526 - mean_absolute_error: 74.0087
Epoch 7/20
13/13 [==============================] - 0s 10ms/step - loss: 7284.0967 - mean_absolute_error: 73.7236
Epoch 8/20
13/13 [==============================] - 0s 10ms/step - loss: 7241.6392 - mean_absolute_error: 73.4337
Epoch 9/20
13/13 [==============================] - 0s 11ms/step - loss: 7197.9258 - mean

NameError: name 'IPython' is not defined